config/routes.rb
Rails.application.routes.draw do
  root "homes#top"
  
  get '/home/about', to: 'homes#about', as: 'about_home'
  
  devise_for :users
  
  resources :users, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :user
  
  validates :title, presence: true
  
  validates :body, presence: true
  validates :body, length: { maximum: 200 }
  
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  
  has_one_attached :image
  
end

app/models/user.rb
class User < ApplicationRecord
  
  require 'user'
  has_one_attached :profile_image
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
         
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { in: 2..20 }
  
  validates :introduction, length: { maximum: 50 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_url
  end

  def get_profile_image(width, height)
    if @user.profile_image.attached?
      image_tag @user.profile_image.variant(resize: "#{width}x#{height}>")
    else
      image_tag 'no_image', size: "#{width}x#{height}"
    end
  end

  protected
  
  def logged_in?
    flash[:notice] = "aaaa"
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  attr_accessor :body

  def new
    @book = Book.new
  end
  
  def create
    puts params.inspect
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end
  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def show
    @book = Book.find(params[:id])
      if @book
        @user = @book.user
      else
      end
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  
  def book_params
  params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    if current_user
      redirect_to user_path(current_user)
    end
  end
  
  def about
      
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def get_profile_image(width, height)
    if current_user.profile_image.attached?
      url = current_user.profile_image.variant(resize: "#{width}x#{height}").url
      return url
    else
    end
  end
  
  def new
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
  end
  
  def about
    if logged_in?
      redirect_to '/users/about'
    else
    end 
  end
  
  def index
    @users = User.all
    @user = current_user
    @user_name = current_user.name
    @books = Book.all
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render 'edit'
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_common.html.erb
<!-- 左側 -->
<div class="col-md-3">

  <h4>User info</h4>
  <% if user.profile_image.attached? %>
    <%= image_tag user.get_profile_image %>
  <% else %>
    <%= image_tag 'no_image', size: "100x100" %>
  <% end %>  
  
  <table class="table table-striped">
    <table class=user_table>
      <tr><th>name</th><th><%= user.name %></th></tr>
      <tr><th>introduction</th><th><%= user.introduction %></th></tr>
    </table></br>
  </table>
  
  <div class="row">
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fa-solid fa-user-gear"></i>
    <% end %>
  </div>

  <div class="row">
    <div class="btn-block edit_user" href="/users/edit">
      <div class= data-icon="user-gear" role="img">
        <path fill="currentColor"></path>
      </div>
    </div>
  </div>

  <h4>New book</h4>
  <%= form_with model: Book.new, url: books_path, method: :post do |f| %>
    <p>Title</p>
    <%= f.text_field :title %>
  	
    <p>Opinion</p>
    <%= f.text_area :body %></br>
  	<%= f.submit 'Create Book' %>
  <% end %>

</div>

app/views/books/edit.html.erb
<h4>books/edit</h4>

<div class="container">

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div class="row">
    <div class="mx-auto">
      
      <h4>Editing Book</h4>
      <%= form_with model: @book do |f| %>
      
        <p>Title</p>
        <%= f.text_field :title, autofocus: true, id:"book_title", placeholder:""%></br></br>
        
        <p>Opinion</p>
        <%= f.text_field :body, autofocus: true, id:"book_body", placeholder:""%></br></br>
        
        <%= f.submit "Update Book" %></br>
      <% end %>
      
      <%=link_to "Show", book_path(@book) %>
      <%=link_to "Back", books_path(@books) %>
      
      
    </div>
  </div>
  </br></br>
</div>

app/views/books/index.html.erb
<h4>books index</h4>

<div class="container">
  
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  
  <div class="row">
    
    <!-- 左側 -->
    <%= render 'books/common', books: @books, user: @user %>
    
    <!-- 右側 -->
    <div class="col-md-8 offset-md-1">
      <h4>Books</h4>
        <table class="table table-striped">
          <table class="books_table">
            <tr>
              <th></th>
              <th>Title</th>
              <th>Option</th>
            </tr>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  <td><%= link_to user_path(book.user.id) do %>
                    <%= image_tag book.user.get_profile_image %>
                  <% end %></td>
                  
                  <td><%=link_to book.title, book_path(book.id) %></td>
                  
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </table>
    </div> 
     
  </div>
</div>

app/views/books/new.html.erb
<h4>New book</h4>
<%= form_with model: Book.new do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
	
  <h4>Opinion</h4>
  <%= f.text_area :body %><br>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<h4>books show</h4>
<div class="container">
  <div class="row">
    
    <!-- 左側 -->
    <%= render 'books/common', books: @books, user: @user %>
    
    <!-- 右側 -->
    <div class="col-md-8 offset-md-1">
      <h4>Book detail</h4>
        <table class="table">
          <tbody>
            <tr>
              <td><%= image_tag @user.get_profile_image %><br>
              <%=link_to @user.name, user_path(@user.id) %></td>
              
              <td><%=link_to @book.title, book_path(@book) %></td>
              
              <td><%= @book.body %></td>
              
              <% if current_user == @book.user %>
                <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-outline-secondary btn-block" %></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger" %></td>
              <% end %>

            </tr>
          </tbody>
        </table>
    </div> 
  </div>
</div>

app/views/homes/about.html.erb
<h4>homes/about</h4>
<html>
  <head>
    <div class="text-center">
      <h1>welcome to <i class="fa-solid fa-book"></i> Bookers !!</h1>
    </div>
  </head>
</html>

app/views/homes/top.html.erb
<h4>homes/top</h4>
<html>
  <main>
    <div class="text-center">
      <h1>welcome to <i class="fa-solid fa-book"></i> Bookers !!</h1>
      <h2>In <i class="fa-solid fa-book"></i> Bookers,</h2>
      you can share and exchange your opinions , inpressions , and emotions<br>
      about various books!
    
    <div class="container">
      <% if user_signed_in? %>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <div class="btn-wrapper col-5 mx-auto">
          <div class="row">
            <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
          </div>  
          <div class="row">
            <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
          </div>  
        </div>
      <% end %>
    </div>
  </main>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <script src="https://kit.fontawesome.com/354c6003fa.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%=  link_to users_path,class: 'nav-link text-light' do %>
                  <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%=  link_to books_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to root_path,class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to about_home_path, class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                  <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                  <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <div>
      <%= flash[:notice] %>
    </div>
    
      <%= yield %>
      
    <footer class="mx-auto">
      <p>CopyRight Infratop.inc</p>
    </footer>
    
  </body>
  
</html>

app/views/users/edit.html.erb
<h4>users/edit</h4>

<div class="container">
  <div class="row">
    <div class="mx-auto">
      
      <h4>User info</h4>
      
      <% if @user.errors.any? %>
        <%= @user.errors.count %>件のエラーが発生しました
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      
      <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
      
        <p>Name</p>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%></br></br>
        
        <p>Image</p>
        <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %></br></br>
        
        <p>Introduction</p>
        <%= f.text_field :introduction, autofocus: true, id:"", placeholder:""%></br></br>
        
        <%= f.submit "Update User" %></br>
      <% end %>
      
    </div>
  </div>
  </br></br>
</div>

app/views/users/index.html.erb
<h4>users index</h4>
<div class="container">
  <div class="row">
    
    <!-- 左側 -->
    <%= render 'books/common', books: @books, user: @user %>
    
    <!-- 右側 -->
    <div class="col-md-8 offset-md-1">
      <h4>Users</h4>
        <table class="table table-striped">
          <table class="books_table">
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
            </tr>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= image_tag user.get_profile_image %></td>
                  <td><%= user.name %></td>
                  <td><%=link_to "Show", user_path(user) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </table>
    </div> 
     
  </div>
</div>

app/views/users/new.html.erb
<h4>users/new</h4>

app/views/users/show.html.erb
<h4>users show</h4>
<div class="container">
  <div class="row">
    
    <!-- 左側 -->
    <%= render 'books/common', books: @books, user: @user %>
    
    <!-- 右側 -->
    <div class="col-md-8 offset-md-1">
      <h4>Books</h4>
        <table class="table table-striped">
          <table class="users_table">
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
            <tbody>
              <% @books.each do |book| %>
                <tr>
                  
                  <td><%= link_to user_path(@user.id) do %>
                  <%= image_tag @user.get_profile_image %>
                  <% end %></td>
                  
                  <td><%=link_to book.title, book_path(book.id) %></td>
                  <td><%= book.body %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </table>
    </div> 
     
  </div>
</div>